// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqOiQUio1bcjYqiQl78g2iHkron0x89jc',
    appId: '1:713580110115:web:81aeed2e43d7c08daf6c96',
    messagingSenderId: '713580110115',
    projectId: 'velo-demo-firebase',
    authDomain: 'velo-demo-firebase.firebaseapp.com',
    storageBucket: 'velo-demo-firebase.appspot.com',
    measurementId: 'G-4HXDXBN2SV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg7xB3ja2XEfis3LhyKM4GZSzHZirOgjI',
    appId: '1:713580110115:android:6b05a82ce3681aaaaf6c96',
    messagingSenderId: '713580110115',
    projectId: 'velo-demo-firebase',
    storageBucket: 'velo-demo-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPGdR0qDOGucXBfQ-34DDxpkaF4DnIctw',
    appId: '1:713580110115:ios:dd0e946893abcd4faf6c96',
    messagingSenderId: '713580110115',
    projectId: 'velo-demo-firebase',
    storageBucket: 'velo-demo-firebase.appspot.com',
    iosClientId: '713580110115-ptcbjt49220oafu377jjhfdp2jgg68ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPGdR0qDOGucXBfQ-34DDxpkaF4DnIctw',
    appId: '1:713580110115:ios:dd0e946893abcd4faf6c96',
    messagingSenderId: '713580110115',
    projectId: 'velo-demo-firebase',
    storageBucket: 'velo-demo-firebase.appspot.com',
    iosClientId: '713580110115-ptcbjt49220oafu377jjhfdp2jgg68ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasedemo',
  );
}
